high_liquidity_symbols:
  - BTCUSDT
  - ETHUSDT
  - BNBUSDT
  - SOLUSDT
  - XRPUSDT
  - ADAUSDT
  - DOGEUSDT
  - AVAXUSDT
  - DOTUSDT
  - LINKUSDT
  - MATICUSDT
  - SUSHIUSDT
  - AAVEUSDT
  - UNIUSDT
  - FTUSDT
  - SANDUSDT
  - AXSUSDT
  - LTCUSDT
  - ETCUSDT